//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lingvo.NER.Rules.TestApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lingvo.NER.Rules.TestApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        table { width: 100%; border-collapse: collapse; line-height: 20px; }
        ///        span { display: table; }
        ///        tr:nth-child(2n+1) { background-color: whitesmoke; }
        ///        th { color: white; background-color: dimgray; border: 1px black solid; white-space: nowrap;}
        ///        td { vertical-align: top; border: 1px silver solid; padding: 5px; }
        ///            th:nth-c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string begin_of_html_1 {
            get {
                return ResourceManager.GetString("begin_of_html_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        table { width: 100%; border-collapse: collapse; line-height: 20px; }
        ///        span { display: table; }
        ///        tr:nth-child(2n+1) { background-color: whitesmoke; }
        ///        th { color: white; background-color: dimgray; border: 1px black solid; white-space: nowrap;}
        ///        td { vertical-align: top; border: 1px silver solid; padding: 5px; }
        ///            th:nth-c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string begin_of_html_2 {
            get {
                return ResourceManager.GetString("begin_of_html_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string end_of_html {
            get {
                return ResourceManager.GetString("end_of_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;    
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;xml-as-html&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot; id=&quot;NER--css&quot;&gt;
        ///        .NER {
        ///            border-bottom: 1px dotted black;
        ///            font-weight: bold;
        ///        }
        ///        .PhoneNumber {
        ///            border-bottom: 1px dotted black;
        ///            font-weight: bold;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ner_xml_2_html__full {
            get {
                return ResourceManager.GetString("ner_xml_2_html__full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;    
        ///    &lt;!--&lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;xml-as-html&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot; id=&quot;NER__css&quot;&gt;
        ///        .NER {
        ///            border-bottom: 1px dotted black;
        ///            font-weight: bold;
        ///        }
        ///        .PhoneNumber {
        ///            border-bottom: 1px dotted black;
        ///            font-weight: bold;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ner_xml_2_html__piece {
            get {
                return ResourceManager.GetString("ner_xml_2_html__piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;    
        ///    &lt;!--
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;xml-as-html&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///    --&gt;
        ///        &lt;!--Courier, Tahoma--&gt;
        ///        &lt;div style=&quot;font-family: Tahoma; font-size: 10pt; margin-bottom: 2em;&quot;&gt;
        ///          &lt;xsl:apply-templates /&gt;
        ///        &lt;/div&gt;
        ///    &lt;!--   
        ///      &lt;/body&gt;
        ///    &lt;/html&gt;
        ///    --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_2_html {
            get {
                return ResourceManager.GetString("xml_2_html", resourceCulture);
            }
        }
    }
}
